version: '2.1'
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    links:
      - frontend1
      - frontend2
    restart: always
  frontend1:
    build: ./frontend
    environment:
      - PORT=8080
    expose:
      - 8080
    restart: always
  frontend2:
    build: ./frontend
    environment:
      - PORT=8080
    expose:
      - 8080
    restart: always
