apiEndpoints:
  api:
    host: '*'

http:
  port: 8080
admin:
  port: 9876
  hostname: localhost

serviceEndpoints:
  frontend:
    urls:
      #### UPDATE ME ####
      - http://fronend1:8080
      - http://fronend2:8080
policies:
  - proxy
pipelines:
  - name: adminAPI
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: frontend
# express gateway supports other policies as well: https://www.express-gateway.io/docs/policies/
# - authentication
# - rate limiting
# - logging
